name: NodeJS with Webpack

on:
  push:
    branches: [ "raytracer" ]
  pull_request:
    branches: [ "raytracer" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build
      run: |
        npm i
        npm run build
    
    - name: Deploy GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2.0.3
