name: NodeJS with Webpack

on:
  push:
    branches: [ "raytracer" ]
  pull_request:
    branches: [ "raytracer" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist # Replace this with the directory containing the built application
        github_token: ${{ secrets.GITHUB_TOKEN }}
